Empezando custom scene
Program-AR/pilas-bloques-exercises pull request #12
Opened 2021-08-30 18:17 UTC by tfloxolodeiro

Resolves https://github.com/Program-AR/pilas-bloques/issues/826

2021-08-30 18:19 UTC, tfloxolodeiro commented on src/escenas/libroPrimaria/CustomScene.ts
> +    switch (actorType) { //Un enum para los actor type seria mejor
Queria hacer que los actorType sea un enum para poder reutilizar el caracter en el error de la linea 42, pero a typescript no le gusta.

2021-08-31 15:10 UTC, asanzo requested changes

2021-08-31 15:10 UTC, asanzo commented on src/escenas/libroPrimaria/CustomScene.ts
> +  }
¿Te parece si tipamos este constructor para tenerlo documentado?

A ver si te cierra este constructor (es una idea):

```typescript
type CustomSceneOptions = {
     grid: GridSpec,
     backgroundImage?: string,  // esto está por verse, de acuerdo a lo que veas, Tom.
     .... // habría que agregar las imágenes / grillas de obstáculos y del autómata, después se agrega acá.
}

type GridSpec = { // debería ir en EscenaDesdeMapa, aunque en ppio no se use en ese archivo, creo
    spec: Spec, // string | string[]
    specOptions: opcionesMapaAleatorio
}

constructor(options: CustomSceneOptions){
   .........
}
```

Estas `CustomSceneOptions` deben comenzar bien mimadas, y prolijas, porque van a crecer de acuerdo a cuántas libertades empiece a tener esta escena.

2021-08-31 15:10 UTC, asanzo commented on src/escenas/libroPrimaria/CustomScene.ts
> +      case 'a': { this.setAutomataFromId(actorId); return this.automata } //polemico
Sí, no entiendo por qué este método tiene efecto, no debería tenerlo.

2021-08-31 15:11 UTC, asanzo commented
Además, me gustaría que esta escena tenga una documentación arriba, una explicación de que se usa para el creador de escenarios de pilas bloques

2021-08-31 17:45 UTC, tfloxolodeiro commented on src/escenas/libroPrimaria/CustomScene.ts
> +**/
No se me ocurrio algo mas descriptivo sin repetir lo que ya dice EscenaDesdeMapa

2021-08-31 17:45 UTC, tfloxolodeiro commented on src/escenas/libroPrimaria/EscenaDesdeMapa.ts
> +    initDesdeUnaOVariasDescripciones(especificacion: Spec, opciones?: opcionesMapaAleatorio) { //Podria recibir un GridSpec directamente
Estaria mejor que reciba un GridSpec, pero habria que cambiarlo en las otras escenas.

2021-09-01 03:16 UTC, asanzo approved these changes

2021-09-01 03:16 UTC, asanzo commented on src/escenas/libroPrimaria/EscenaDesdeMapa.ts
> +    initDesdeUnaOVariasDescripciones(especificacion: Spec, opciones?: opcionesMapaAleatorio) { //Podria recibir un GridSpec directamente
Sí, y hay que cambiar otras cosas, como que opcionesMapaAleatorio debería como mínimo estar en mayúscula y no sé si en inglés, pero no importa. Enfoquémonos en sacar andando la customscene

2021-09-01 03:16 UTC, asanzo commented on src/escenas/libroPrimaria/CustomScene.ts
> +**/
Pilas Bloques con mayúsculas (respetemos el branding).  
Y en inglés, porfa.

El código escrito es medio incambiable, todo pilasbloques exercises es enorme, y los template methods te atan al español. Sin embargo, está bueno que un angloparlante pueda usar la CustomScene aunque no pueda codearla.

2021-09-01 03:17 UTC, asanzo commented
Ah, y Tom te voy a pedir si podés probar el #11 y mergearlo también.

2021-09-14 21:32 UTC, asanzo commented on tests/customScene.spec.ts
> +    escena = new CustomScene({ grid: { spec: "[aL,p1,o1,-,-,-,-,-,-]" }, images: [{ id: `${objectTypes.obstacle.idPath}/1`, url: 'obstacle.png' }, { id: `${objectTypes.prize.idPath}/1`, url: 'prize.p
Revisar si no hay que mandarle el mensaje "iniciar"

2021-09-14 21:34 UTC, asanzo commented on src/actores/libroPrimaria/Lita.ts
> +		this.definirAnimacion("recoger", [0,0,63,63,64,65,66,67,68,69,69,70,70,71,71,72,72,72], 12);
Esto sería necesario para los otros 3 personajes también, ¿verdad? Lo cual me pone a pensar si no tenemos que agregar animaciones a los 4.

2021-09-14 21:34 UTC, asanzo commented on tests/customScene.spec.ts
> +    expect(pilas.obtener_actores_con_etiqueta(objectTypes.obstacle.tag)).toBe(1)
falta un length acá?

2021-09-27 17:34 UTC, asanzo commented
Para seguir probando cómo testear:

https://github.com/tom-sherman/blog/blob/master/posts/02-running-jest-tests-in-a-browser.md

https://jasmine.github.io/setup/browser.html

Objetivo:

- Poder escribir los tests en typescript
- Que los tests corran en un navegador (o emulador de)
- No tener que repetir demasiado los pasos de compilación entre la configuración de los tests y la configuración del build.

2021-10-13 15:34 UTC, merged