fix-futbol-robot
Program-AR/pilas-bloques-exercises pull request #8
Opened 2020-07-23 06:21 UTC by 51lv3str1

Soluciona parcialmente el issue [Error en condición de desafío realizado en Futbol de Robots ]( https://github.com/Program-AR/pilas-bloques/issues/586)

2020-07-27 17:06 UTC, PalumboN reviewed
:ok_hand: 

- No hay tests en este proyecto?
- Por qué decís que se arregló **parcialmente**?

2020-07-27 17:06 UTC, PalumboN commented on dist/pilas-bloques-exercises.js
> -;// Generated automatically by nearley, version 2.17.0
Estos `dist`s están bien tenerlos en el repo :thinking: ??

2020-07-27 17:06 UTC, PalumboN commented on src/comportamientos/Interactuar.ts
>      }
Por qué no `receptor()`??

2020-07-27 17:06 UTC, PalumboN commented on src/comportamientos/SerPateado.ts
> +    this.receptor.pateado = true
Para qué este flag?

2020-07-27 18:31 UTC, 51lv3str1 commented
> * No hay tests en este proyecto?
> * Por qué decís que se arregló **parcialmente**?

parcialmente, por que tenes que mergear luego el pr del frontend para que el issue se cierre :p

2020-07-27 18:33 UTC, 51lv3str1 commented on src/comportamientos/SerPateado.ts
> +    this.receptor.pateado = true
es clave, es con lo que yo se que la pelota fue pateada y por consecuente no puede ser considerada pateable nuevamente luego de que fue pateada.

2020-07-27 18:34 UTC, 51lv3str1 commented on dist/pilas-bloques-exercises.js
> -;// Generated automatically by nearley, version 2.17.0
Ahora no recuerdo bien por que lo teníamos precompilado esto, en todo caso se tiene que poder automatizar. Pero son los ejercicios de pilas bloques ya compilados.

2020-07-27 19:03 UTC, 51lv3str1 commented on src/comportamientos/Interactuar.ts
>      }
por que no existe el método :p

2020-07-29 19:45 UTC, asanzo requested changes
Atento al cambio de verificaciones. Lo demás son cambios de forma, discusiones secundarias :D

2020-07-29 19:45 UTC, asanzo commented on src/comportamientos/Interactuar.ts
> +    }
¿Queremos poner un accesor para cada cosa de argumentos? ¿No es un montón de código al dope? En los comportamientos en general se accede directo a los argumentos.

2020-07-29 19:45 UTC, asanzo commented on src/comportamientos/Interactuar.ts
> +    }
La que sí te banco es la de no hacer foo['bar'] y sí hacer foo.bar. No sé por qué están como strings, es verboso al pedo.

2020-07-29 19:45 UTC, asanzo commented on src/comportamientos/PatearPelota.ts
> +    }
Evitaría los protected y private. No sé qué opinan al respecto @51lv3str1 @PalumboN

2020-07-29 19:45 UTC, asanzo commented on src/comportamientos/SerPateado.ts
> +    this.receptor.pateado = true
Estoy de acuerdo con que el flag es necesario. Pero no estoy de acuerdo con que hay que sobreescribir este método. Abajo aclaro.

2020-07-29 19:45 UTC, asanzo commented on src/comportamientos/Interactuar.ts
>      }
De todas formas, teniendo en cuenta que para todo comportamiento, se entiende que el receptor es el que lo ejecuta, no metería otra palabrita más "interactor". Por simplicidad: recordá que el receptor es el que hace el comportamiento y ya. En la línea `chabón.hacer(Interactuar, {etiqueta: 'Pelota'....})` sabés después que el `receptor` es el chabón y el `interactuado` es la pelota que está tocando ahora. El receptor siempre es el chabón, en cualquier comportamiento. Me gustaría no cambiarle el nombre en cada comportamiento (sino en "recoger" debería llamarse "recogedor", etc.)
¿Por qué la habías puesto?

2020-07-29 19:45 UTC, asanzo commented on src/comportamientos/PatearPelota.ts
> +    }
Yo no redefiniría este método. Por lo que menciono en el PR de Pilas Bloques sobre que esto tiene un problema. Explico un poco: como en Interactuar el código es este:

```Typescript
#Interactuar>>configurarVerificaciones(): void {
        const mensajeError: string = this.mensajeDeError() || "¡Acá no hay " + this.hacerLegible(this.etiqueta()) + "!"
        this.verificacionesPre.push(new Verificacion(() => this.hayConQuienInteractuar(), mensajeError))
    }
```

Lo que hace `hayConQuienInteractuar` es darme la pregunta para luego tirar el error "no hay pelota".

Lo que vos querés hacer es agregar otra verificación:


```suggestion
    configurarVerificaciones(): void {
        super.configurarVerificaciones()
        this.verificacionesPre.push(new Verificacion(() => !!this.interactuado().pateado, "No puedo patear dos veces la misma pelota"))
    }
```

2020-07-29 19:46 UTC, asanzo commented
Ah, y recordar releasear luego de mergear

2020-07-30 01:57 UTC, 51lv3str1 commented on src/comportamientos/PatearPelota.ts
> +    }
a mi no me molestan, si queres dejamos todos los métodos en publico.

2020-07-30 01:58 UTC, 51lv3str1 commented on src/comportamientos/PatearPelota.ts
> +    }
me gusta, me gusta

2020-07-30 19:26 UTC, PalumboN commented on src/comportamientos/Interactuar.ts
> +    }
Lo piola de esto es que se puede sobreescribir no hacer magias de pre-cálculo en los constructores :+1:

2020-07-30 19:26 UTC, PalumboN commented on src/comportamientos/PatearPelota.ts
> +    }
Para mí está bueno si no molestan, sobre todo para entender los template methods.

2020-07-30 19:30 UTC, asanzo commented on src/comportamientos/PatearPelota.ts
> +    }
Ok!

2020-07-30 22:24 UTC, 51lv3str1 commented on src/comportamientos/Interactuar.ts
> +    }
Banco mucho esto que dice el @PalumboN ,así lo pensé yo.

2020-07-31 02:33 UTC, 51lv3str1 commented
Le erre con la idea de tener un actor pateable, no va con la idea de habilidades.

2020-07-31 19:42 UTC, asanzo commented on src/comportamientos/Interactuar.ts
>      }
¿Qué onda esto?

2020-07-31 21:18 UTC, 51lv3str1 commented on src/comportamientos/Interactuar.ts
>      }
Me pareció bien lo que dijiste, me pareció correcto y por eso lo elimine, ¿me perdí de algo?

2020-07-31 23:52 UTC, asanzo commented on src/comportamientos/Interactuar.ts
>      }
Uf, estaba haciendo el review y fui cerrando lo que ya estaba, y me pareció ver el interactor todavía.  Fui a revisar y ahora no está, perdón :yum:

2020-07-31 23:53 UTC, merged

2020-07-31 23:55 UTC, asanzo commented
Listo @51lv3str1 !! te hacés el release desde master?